# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='rank',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
